apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-srv-cap-xs-app
data:
  xs-app.json: |-
    {
      "welcomeFile": "/index.html",
      "authenticationMethod": "route",
      "routes": [
        {
          "source": "^/orders/(.*)$",
          "target": "/orders/$1",
          "destination": "srv-api",
          "authenticationType": "xsuaa",
          "csrfProtection": false
        },
        {
          "source": "^/resources/(.*)$",
          "target": "/resources/$1",
          "authenticationType": "none",
          "destination": "ui5"
        },
        {
          "source": "^/test-resources/(.*)$",
          "target": "/test-resources/$1",
          "authenticationType": "none",
          "destination": "ui5"
        },
        {
          "source": "^(.*)$",
          "target": "/comkymademoorders/$1",
          "service": "html5-apps-repo-rt",
          "authenticationType": "xsuaa"
        }
      ]
    }
