apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: orders-srv-cap-approuter
  name: orders-srv-cap-approuter
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: orders-srv-cap-approuter
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE"]
      service:
        name: orders-srv-cap-approuter
        port: 5000
      accessStrategies:
        - handler: noop
      mutators:
        - handler: header
          config:
            headers:
              x-forwarded-host: "orders-srv-cap-approuter.{CLUSTER_DOMAIN}"
